# Generated by Django 2.2.19 on 2023-03-13 23:54


import json
import os

from django.db import migrations

INITIAL_TAGS = [
    {'color': '#4287f5', 'name': 'Завтрак', 'slug': 'breakfast'},
    {'color': '#f55d42', 'name': 'Обед', 'slug': 'dinner'},
    {'color': '#42f587', 'name': 'Ужин', 'slug': 'supper'},
    {'color': '#d142f5', 'name': 'Снэк', 'slug': 'snack'},
    {'color': '#daf542', 'name': 'Детское', 'slug': 'kids'},
]


def add_ingredients(apps, schema_editor):
    Ingredient = apps.get_model("recipes", "Ingredient")
    with open('./data/ingredients.json') as json_file:
        data = json.load(json_file)
    for ingredient in data:
        new_ingredient = Ingredient(name=ingredient['name'],
                                    measurement_unit=ingredient['measurement_unit'])
        new_ingredient.save()


def remove_ingredients(apps, schema_editor):
    Ingredient = apps.get_model("recipes", "Ingredient")
    with open(os.path.join('data', 'ingredients.json')) as json_file:
        data = json.load(json_file)
    for ingredient in data:
        Ingredient.objects.get(name=ingredient['name']).delete()


def add_tags(apps, schema_editor):
    Tag = apps.get_model("recipes", "Tag")
    for tag in INITIAL_TAGS:
        new_tag = Tag(color=tag['color'], name=tag['name'], slug=tag['slug'])
        new_tag.save()


def remove_tags(apps, schema_editor):
    Tag = apps.get_model("recipes", "Tag")
    for tag in INITIAL_TAGS:
        Tag.objects.get(slug=tag['slug']).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_auto_20230313_2354'),
    ]

    operations = [
        migrations.RunPython(
            add_tags,
            remove_tags
        ),
        migrations.RunPython(
            add_ingredients,
            remove_ingredients
        ),
    ]
